# Generated by Django 5.2.5 on 2025-09-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peptitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
