# Generated by Django 5.2.5 on 2025-09-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptitions', '0002_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='petitions/'),
        ),
    ]
