# Generated by Django 4.2.14 on 2025-11-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptitions', '0003_petition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='category',
            field=models.CharField(choices=[('environment', 'Environment'), ('human_rights', 'Human Rights'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('animal_welfare', 'Animal Welfare'), ('social_justice', 'Social Justice'), ('technology', 'Technology'), ('politics', 'Politics'), ('economy', 'Economy'), ('arts_culture', 'Arts & Culture'), ('sports', 'Sports'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
